name: 🎬 Auto Reel Processor

on:
  repository_dispatch:
    types: [new_reel_link]   # Must match the "event_type" from your n8n HTTP Request

jobs:
  process_reel:
    name: Process Instagram Reel
    runs-on: ubuntu-latest

    env:
      PYTHONUNBUFFERED: 1
      GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
      LOG_LEVEL: INFO

    steps:
      # -------------------------------
      # 1️⃣ Checkout Repository
      # -------------------------------
      - name: 🧩 Checkout Repo
        uses: actions/checkout@v3

      # -------------------------------
      # 2️⃣ Set up Python Environment
      # -------------------------------
      - name: 🐍 Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # -------------------------------
      # 3️⃣ Install Dependencies
      # -------------------------------
      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # -------------------------------
      # 4️⃣ Get Payload (Instagram URL)
      # -------------------------------
      - name: 🔗 Get Reel Link
        id: getlink
        run: |
          echo "INSTAGRAM_URL=${{ github.event.client_payload.instagram_url }}" >> $GITHUB_ENV
          echo "🎯 Reel URL: ${{ github.event.client_payload.instagram_url }}"

      # -------------------------------
      # 5️⃣ Create Job JSON (Metadata)
      # -------------------------------
      - name: 🗂️ Create Job Metadata
        run: |
          mkdir -p jobs/split
          echo "{ \"reel_url\": \"${INSTAGRAM_URL}\", \"job_id\": \"$(date +%s)\" }" > jobs/split/job_${{ github.run_id }}.json
          echo "Created jobs/split/job_${{ github.run_id }}.json"

      # -------------------------------
      # 6️⃣ Download Reel
      # -------------------------------
      - name: ⬇️ Download Reel Video
        run: |
          python scripts/download_reel.py jobs/split/job_${{ github.run_id }}.json

      # -------------------------------
      # 7️⃣ Process Video (Crop + Text + Logo)
      # -------------------------------
      - name: 🎨 Process Video with AI Cropping
        run: |
          python scripts/process_video.py jobs/split/job_${{ github.run_id }}.json

      # -------------------------------
      # 8️⃣ Upload to Google Drive
      # -------------------------------
      - name: ☁️ Upload Processed Video to Google Drive
        run: |
          python scripts/upload_drive.py jobs/split/job_${{ github.run_id }}.json

      # -------------------------------
      # 9️⃣ Save Artifacts (Optional)
      # -------------------------------
      - name: 🧱 Upload Logs & Output as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: processed_output
          path: |
            jobs/split/
            output/

      # -------------------------------
      # 🔟 Success Message
      # -------------------------------
      - name: ✅ Job Completed
        run: echo "🎉 Processing completed successfully for ${{ github.event.client_payload.instagram_url }}"
